version: "3"
services:
  api-server:
    # build: .
    build: ../../
    command: yarn start:prod
    # env_file: ./config/dev.env
    env_file: ./.env
    ports:
      - "5000:5000"
    networks:
      - integra.do-node-app
    volumes:
      # - ./:/usr/src/app
      - ../../:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - integra.do-node-app
    volumes:
      - mongo-data:/data/db
networks:
  integra.do-node-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local